const faqDataEn=[
["Can foreigners invest in property in Indonesia?","Yes, foreign buyers can invest in Indonesian property through compliant legal structures. The correct structure depends on the buyer profile, intended use and legal due diligence. Full legal guidance is provided before reservation."],
["Is this project freehold?","A secure ownership structure is available, subject to legal due diligence and local regulations. Final ownership structure will be reviewed with legal advisors before any reservation is completed."],
["Where is the project located?","The project is located in the Mandalika area of South Lombok, close to the international MotoGP circuit, beaches, restaurants and tourism infrastructure."],
["How many villas are available?","Only 11 private villas are planned."],
["What is included in each villa?","Each villa includes approximately 70 m² of built area, one bedroom, indoor-outdoor living, a private pool, terrace and tropical landscaping."],
["What is the starting price?","Villas start from €120,000. Final pricing may vary depending on release phase, specifications and availability."],
["Can I rent out the villa?","The villas are designed for personal use and rental potential. Optional property management support will be available."],
["What is the payment plan?","The preliminary payment plan is 25% reservation deposit, 30% pre-construction, 35% during build progress and 10% at final handover."],
["Can I buy without travelling to Lombok?","Remote purchase support may be available through legal representatives and digital documentation, subject to legal process and buyer verification."],
["Can I visit the land?","Yes. Site visits can be arranged for interested buyers and investors."]
];
const accordions=document.querySelector("#accordions");
const faqDataEs=[
["¿Pueden los extranjeros invertir en propiedades en Indonesia?","Sí, los compradores extranjeros pueden invertir mediante estructuras legales que cumplan la normativa indonesia. La estructura adecuada depende del perfil del comprador, el uso previsto y la diligencia debida legal. Se proporciona asesoramiento legal completo antes de reservar."],
["¿Es este proyecto freehold?","Hay disponible una estructura de propiedad segura, sujeta a diligencia debida legal y normativa local. La estructura final se revisará con asesores legales antes de completar cualquier reserva."],
["¿Dónde está ubicado el proyecto?","El proyecto está ubicado en la zona de Mandalika, en el sur de Lombok, cerca del circuito internacional de MotoGP, playas, restaurantes e infraestructura turística."],
["¿Cuántas villas hay disponibles?","Solo se proyectan 11 villas privadas."],
["¿Qué incluye cada villa?","Cada villa incluye aproximadamente 70 m² construidos, un dormitorio, espacios interiores y exteriores, piscina privada, terraza y paisajismo tropical."],
["¿Cuál es el precio inicial?","Las villas parten de 120.000 €. El precio final puede variar según la fase de lanzamiento, las especificaciones y la disponibilidad."],
["¿Puedo alquilar la villa?","Las villas están diseñadas para uso personal y potencial de alquiler. Habrá disponible un servicio opcional de gestión de la propiedad."],
["¿Cuál es el plan de pagos?","El plan preliminar es un 25 % como depósito de reserva, un 30 % antes de la construcción, un 35 % durante el avance de obra y un 10 % en la entrega final."],
["¿Puedo comprar sin viajar a Lombok?","Puede haber asistencia para la compra remota mediante representantes legales y documentación digital, sujeta al proceso legal y la verificación del comprador."],
["¿Puedo visitar el terreno?","Sí. Se pueden organizar visitas al terreno para compradores e inversores interesados."]
];
function renderDynamic(lang){const data=lang==="es"?faqDataEs:faqDataEn;accordions.innerHTML=data.map((item,i)=>`<article class="accordion"><button aria-expanded="false"><b>${String(i+1).padStart(2,"0")}</b><span>${item[0]}</span><i>↘</i></button><p>${item[1]}</p></article>`).join("");accordions.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{const item=button.parentElement;item.classList.toggle("open");button.setAttribute("aria-expanded",item.classList.contains("open"))}));document.querySelector("#units").innerHTML=Array.from({length:11},(_,i)=>`<div class="unit"><b>${String(i+1).padStart(2,"0")}</b><span>${lang==="es"?"Disponible próximamente":"Available soon"}</span></div>`).join("")}
const header=document.querySelector("#header"),menu=document.querySelector(".menu");
addEventListener("scroll",()=>header.classList.toggle("scrolled",scrollY>30));
menu.addEventListener("click",()=>{header.classList.toggle("open");menu.setAttribute("aria-expanded",header.classList.contains("open"))});
document.querySelectorAll(".header nav a").forEach(a=>a.addEventListener("click",()=>header.classList.remove("open")));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add("visible")),{threshold:.1});
document.querySelectorAll(".reveal").forEach(element=>observer.observe(element));
document.querySelector("#lead-form").addEventListener("submit",event=>{event.preventDefault();const button=event.currentTarget.querySelector("button");button.textContent="Thank you — enquiry received";button.disabled=true});

const translations={
"Location":"Ubicación","Investment":"Inversión","Payment Plan":"Plan de pagos","Request Brochure":"Solicitar dossier","Check Availability":"Consultar disponibilidad","Conceptual imagery":"Imágenes conceptuales",
"Own one of only 11 private pool villas near Mandalika Circuit":"Hazte con una de las únicas 11 villas con piscina privada cerca del circuito de Mandalika",
"A limited boutique collection of 70 m² tropical villas in South Lombok, each with a private pool, designed for personal use, rental potential and long-term ownership.":"Una colección boutique limitada de villas tropicales de 70 m² en el sur de Lombok, cada una con piscina privada, pensadas para uso personal, potencial de alquiler y propiedad a largo plazo.",
"11 Villas Only":"Solo 11 villas","70 m² Each":"70 m² cada una","Private Pool":"Piscina privada","From €120,000":"Desde 120.000 €","Near MotoGP Circuit":"Cerca del circuito de MotoGP",
"Limited boutique supply":"Oferta boutique limitada","Personal use and rental potential":"Uso personal y potencial de alquiler","Full legal guidance before reservation":"Asesoramiento legal completo antes de reservar",
"Why Lombok":"Por qué Lombok","An early-stage island destination next to Bali":"Un destino insular emergente junto a Bali",
"Lombok is emerging as one of Indonesia’s most compelling property and lifestyle destinations. Located next to Bali but still less saturated, the island offers a rare combination of natural beauty, improving infrastructure, international tourism appeal and a calmer, more authentic atmosphere.":"Lombok está emergiendo como uno de los destinos inmobiliarios y de estilo de vida más atractivos de Indonesia. Situada junto a Bali, pero todavía menos saturada, la isla combina belleza natural, infraestructuras en desarrollo, atractivo turístico internacional y un ambiente más tranquilo y auténtico.",
"Next to Bali":"Junto a Bali","A quieter, less saturated alternative with strong lifestyle appeal.":"Una alternativa más tranquila y menos saturada, con gran atractivo para disfrutarla.",
"Tourism Momentum":"Impulso turístico","Growing attention from domestic and international travellers.":"Atención creciente de viajeros nacionales e internacionales.","Natural Beauty":"Belleza natural","Beaches, surf breaks, waterfalls, Mount Rinjani and the Gili Islands.":"Playas, olas para surfear, cascadas, el monte Rinjani y las islas Gili.","More Accessible Entry":"Entrada más accesible","A more accessible entry point compared to mature Bali hotspots.":"Un punto de entrada más accesible frente a las zonas consolidadas de Bali.",
"Why Mandalika":"Por qué Mandalika","Mandalika is becoming South Lombok’s most watched destination":"Mandalika se está convirtiendo en el destino más observado del sur de Lombok",
"Mandalika sits at the centre of South Lombok’s next phase: international motorsport, coastal tourism, restaurants, beaches, surf culture and infrastructure improvements are bringing new visibility to the area.":"Mandalika está en el centro de la nueva etapa del sur de Lombok: el automovilismo internacional, el turismo costero, los restaurantes, las playas, la cultura del surf y las mejoras de infraestructuras están dando nueva visibilidad a la zona.",
"South Lombok · Indonesia":"Sur de Lombok · Indonesia","Mandalika International Circuit":"Circuito Internacional de Mandalika","Lombok International Airport":"Aeropuerto Internacional de Lombok","Surf & Beach Lifestyle":"Estilo de vida de surf y playa","Restaurants & Tourism Infrastructure":"Restaurantes e infraestructura turística",
"MotoGP demand anchor":"MotoGP como motor de demanda","Global attention, minutes from your villa":"Atención mundial, a minutos de tu villa",
"The Mandalika International Circuit has placed South Lombok on the global tourism map. Each MotoGP season brings international visibility, media attention and strong short-term accommodation demand to the area.":"El Circuito Internacional de Mandalika ha situado al sur de Lombok en el mapa turístico mundial. Cada temporada de MotoGP aporta visibilidad internacional, atención mediática y una fuerte demanda estacional de alojamiento.",
"Request Location Details":"Solicitar detalles de ubicación","International sport tourism":"Turismo deportivo internacional","Minutes from the project":"A minutos del proyecto","Global visibility":"Visibilidad mundial","Seasonal accommodation demand":"Demanda estacional de alojamiento","South Lombok destination":"Destino del sur de Lombok",
"The villa":"La villa","Private tropical living, built for flexibility":"Vida tropical privada, diseñada para adaptarse","70 m² built area":"70 m² construidos","Private swimming pool":"Piscina privada","One spacious bedroom":"Un dormitorio amplio","Indoor-outdoor living":"Vida interior y exterior","Private terrace":"Terraza privada","Tropical landscaping":"Paisajismo tropical","Optional rental management":"Gestión de alquiler opcional",
"Investment Highlights":"Aspectos destacados de inversión","A limited and tangible real estate opportunity":"Una oportunidad inmobiliaria limitada y tangible","Designed around a clear product, an accessible entry point and flexible use in an early-stage destination.":"Un producto definido, un punto de entrada accesible y un uso flexible en un destino emergente.",
"Limited Supply":"Oferta limitada","Only 11 private pool villas planned.":"Solo se proyectan 11 villas con piscina privada.","Entry Price":"Precio de entrada","Private Pool Villas":"Villas con piscina privada","Each villa includes 70 m² built area and a private swimming pool.":"Cada villa incluye 70 m² construidos y piscina privada.","Mandalika Location":"Ubicación en Mandalika","Minutes from the international MotoGP circuit and South Lombok’s beaches.":"A minutos del circuito internacional de MotoGP y de las playas del sur de Lombok.","Rental Potential":"Potencial de alquiler","Designed for personal use, holiday stays and optional managed rental operations.":"Diseñadas para uso personal, estancias vacacionales y alquiler gestionado opcional.","Ownership Guidance":"Asesoramiento sobre propiedad","Full legal guidance available before reservation.":"Asesoramiento legal completo disponible antes de reservar.",
"Simple staged payment plan":"Plan de pagos sencillo por etapas","Four clear milestones from reservation to final documentation.":"Cuatro hitos claros desde la reserva hasta la documentación final.","Reservation Deposit":"Depósito de reserva","Secure your unit with an initial deposit.":"Asegura tu unidad con un depósito inicial.","Pre-Construction":"Preconstrucción","Due one month before construction begins.":"A pagar un mes antes del inicio de las obras.","Build Progress":"Avance de obra","Due when foundation, elevation and structural walls are completed.":"A pagar cuando estén completados los cimientos, la elevación y los muros estructurales.","Final Transfer":"Transferencia final","Due at handover of certificates and final documentation.":"A pagar con la entrega de certificados y documentación final.",
"Hands-free ownership":"Propiedad sin complicaciones","You own the villa. The operational complexity can be managed for you.":"La villa es tuya. La gestión operativa puede hacerse por ti.",
"Maintenance":"Mantenimiento","Cleaning":"Limpieza","Guest preparation":"Preparación para huéspedes","Rental coordination":"Coordinación de alquileres","Security":"Seguridad","Reporting":"Informes","Optional property management":"Gestión opcional de la propiedad",
"Private Release":"Lanzamiento privado","Only 11 villas planned":"Solo 11 villas proyectadas","Request current availability before selecting a unit.":"Consulta la disponibilidad actual antes de elegir una unidad.","Available soon":"Disponible próximamente",
"Details, clearly explained":"Detalles explicados con claridad","Frequently asked questions":"Preguntas frecuentes","Important answers on the location, villa, legal process and purchase journey.":"Respuestas importantes sobre la ubicación, la villa, el proceso legal y la compra.",
"Inside the brochure":"Dentro del dossier","Everything needed for a considered next step":"Todo lo necesario para dar el siguiente paso","Villa specifications":"Especificaciones de la villa","Conceptual renders":"Renders conceptuales","Location overview":"Resumen de ubicación","Ownership guidance":"Asesoramiento sobre propiedad","Availability details":"Detalles de disponibilidad",
"Limited Mandalika release":"Lanzamiento limitado en Mandalika","Secure your place in a limited Mandalika release":"Asegura tu plaza en un lanzamiento limitado en Mandalika","Speak on WhatsApp":"Hablar por WhatsApp","Name":"Nombre","Country":"País","Buyer profile":"Perfil de comprador","Select an option":"Selecciona una opción","Investor":"Inversor","Lifestyle buyer":"Comprador de estilo de vida","Looking for rental income":"Busco ingresos por alquiler","Just researching":"Solo estoy investigando","Message":"Mensaje","I want to receive the brochure and availability details.":"Quiero recibir el dossier y los detalles de disponibilidad.","Brochure":"Dossier","Contact":"Contacto",
"The architecture":"La arquitectura","Limestone, wood and tropical light":"Caliza, madera y luz tropical","A serene palette of natural materials connects every room with the garden and private pool.":"Una paleta serena de materiales naturales conecta cada estancia con el jardín y la piscina privada.","Indoor-outdoor living":"Vida interior y exterior","Serene bedroom":"Dormitorio sereno","Tropical bathroom":"Baño tropical"
};
const originalText=new Map(),originalPlaceholders=new Map();
document.querySelectorAll("body *").forEach(el=>Array.from(el.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE&&n.nodeValue.trim()).forEach(n=>originalText.set(n,n.nodeValue)));
document.querySelectorAll("[placeholder]").forEach(el=>originalPlaceholders.set(el,el.placeholder));
function setLanguage(lang){
 originalText.forEach((raw,node)=>{const key=raw.trim();node.nodeValue=lang==="es"&&translations[key]?raw.replace(key,translations[key]):raw});
 originalPlaceholders.forEach((raw,el)=>{const ph={"Your name":"Tu nombre","Country of residence":"País de residencia","Tell us what you would like to know":"Cuéntanos qué te gustaría saber"};el.placeholder=lang==="es"?(ph[raw]||raw):raw});
 document.documentElement.lang=lang;
 document.title=lang==="es"?"Mandalika Eleven Villas | Villas con piscina privada en Lombok desde 120.000 €":"Mandalika Eleven Villas | Private Pool Villas in Lombok from €120,000";
 document.querySelector('meta[name="description"]').content=lang==="es"?"Una colección limitada de 11 villas con piscina privada en Mandalika, Lombok, cerca del circuito internacional de MotoGP. Desde 120.000 €.":"A limited collection of 11 private pool villas in Mandalika, Lombok, near the international MotoGP circuit. Villas from €120,000.";
 document.querySelectorAll(".language-switch button").forEach(button=>button.classList.toggle("active",button.dataset.lang===lang));
 renderDynamic(lang);
 localStorage.setItem("mandalika-lang",lang);
}
document.querySelectorAll(".language-switch button").forEach(button=>button.addEventListener("click",()=>setLanguage(button.dataset.lang)));
setLanguage(localStorage.getItem("mandalika-lang")||"es");
